/*** Autogenerated by ZIDL 1.0 from aggregate_return.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __aggregate_return_h__
#define __aggregate_return_h__

/* Forward declarations */

#ifndef __AggregateReturnInterface_FWD_DEFINED__
#define __AggregateReturnInterface_FWD_DEFINED__
typedef interface AggregateReturnInterface AggregateReturnInterface;
#ifdef __cplusplus
interface AggregateReturnInterface;
#endif /* __cplusplus */
#endif

/* Headers for imported files */


#ifdef __cplusplus
extern "C" {
#endif

typedef struct AGGREGATE_RETURN {
    int Arg1;
    int Arg2;
} AGGREGATE_RETURN;
/*****************************************************************************
 * AggregateReturnInterface interface
 */
#ifndef __AggregateReturnInterface_INTERFACE_DEFINED__
#define __AggregateReturnInterface_INTERFACE_DEFINED__

DEFINE_GUID(IID_AggregateReturnInterface, 0x554e41e8, 0xae8e, 0x4a8c, 0xb7,0xd2, 0x5b,0x4f,0x27,0x4a,0x30,0xe4);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("554e41e8-ae8e-4a8c-b7d2-5b4f274a30e4")
AggregateReturnInterface
{
#ifdef WIDL_EXPLICIT_AGGREGATE_RETURNS
    virtual AGGREGATE_RETURN * STDMETHODCALLTYPE GetDesc(
        AGGREGATE_RETURN *__ret) = 0;
    AGGREGATE_RETURN STDMETHODCALLTYPE GetDesc(
        )
    {
        AGGREGATE_RETURN __ret;
        return *GetDesc(&__ret);
    }
#else
    virtual AGGREGATE_RETURN STDMETHODCALLTYPE GetDesc(
        ) = 0;
#endif

#ifdef WIDL_EXPLICIT_AGGREGATE_RETURNS
    virtual AGGREGATE_RETURN * STDMETHODCALLTYPE GetDescArg(
        AGGREGATE_RETURN *__ret,
        int a) = 0;
    AGGREGATE_RETURN STDMETHODCALLTYPE GetDescArg(
        int a)
    {
        AGGREGATE_RETURN __ret;
        return *GetDescArg(&__ret,a);
    }
#else
    virtual AGGREGATE_RETURN STDMETHODCALLTYPE GetDescArg(
        int a) = 0;
#endif

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(AggregateReturnInterface, 0x554e41e8, 0xae8e, 0x4a8c, 0xb7,0xd2, 0x5b,0x4f,0x27,0x4a,0x30,0xe4)
#endif
#else
typedef struct AggregateReturnInterfaceVtbl {
    BEGIN_INTERFACE

    /*** AggregateReturnInterface methods ***/
    AGGREGATE_RETURN * (STDMETHODCALLTYPE *GetDesc)(
        AggregateReturnInterface *This,
        AGGREGATE_RETURN *__ret);

    AGGREGATE_RETURN * (STDMETHODCALLTYPE *GetDescArg)(
        AggregateReturnInterface *This,
        AGGREGATE_RETURN *__ret,
        int a);

    END_INTERFACE
} AggregateReturnInterfaceVtbl;

interface AggregateReturnInterface {
    CONST_VTBL AggregateReturnInterfaceVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** AggregateReturnInterface methods ***/
#define AggregateReturnInterface_GetDesc(This) AggregateReturnInterface_GetDesc_define_WIDL_C_INLINE_WRAPPERS_for_aggregate_return_support
#define AggregateReturnInterface_GetDescArg(This,a) AggregateReturnInterface_GetDescArg_define_WIDL_C_INLINE_WRAPPERS_for_aggregate_return_support
#else
/*** AggregateReturnInterface methods ***/
static inline AGGREGATE_RETURN AggregateReturnInterface_GetDesc(AggregateReturnInterface* This) {
    AGGREGATE_RETURN __ret;
    return *This->lpVtbl->GetDesc(This,&__ret);
}
static inline AGGREGATE_RETURN AggregateReturnInterface_GetDescArg(AggregateReturnInterface* This,int a) {
    AGGREGATE_RETURN __ret;
    return *This->lpVtbl->GetDescArg(This,&__ret,a);
}
#endif
#endif

#endif


#endif  /* __AggregateReturnInterface_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __aggregate_return_h__ */
