/*** Autogenerated by ZIDL 1.0 from version.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __version_h__
#define __version_h__

/* Forward declarations */

#ifndef __IWinTypesBase_FWD_DEFINED__
#define __IWinTypesBase_FWD_DEFINED__
typedef interface IWinTypesBase IWinTypesBase;
#ifdef __cplusplus
interface IWinTypesBase;
#endif /* __cplusplus */
#endif

/* Headers for imported files */


#ifdef __cplusplus
extern "C" {
#endif

/*****************************************************************************
 * IWinTypesBase interface (v0.1)
 */
#ifndef __IWinTypesBase_INTERFACE_DEFINED__
#define __IWinTypesBase_INTERFACE_DEFINED__

extern RPC_IF_HANDLE IWinTypesBase_v0_1_c_ifspec;
extern RPC_IF_HANDLE IWinTypesBase_v0_1_s_ifspec;

DEFINE_GUID(IID_IWinTypesBase, 0xb1bea154, 0x1c2f, 0x4da9, 0x9a,0xbf, 0x6e,0x2d,0x24,0xee,0xa1,0xbe);
#endif  /* __IWinTypesBase_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __version_h__ */
