/*** Autogenerated by ZIDL 1.0 from void.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __void_h__
#define __void_h__

/* Forward declarations */

#ifndef __IClass_FWD_DEFINED__
#define __IClass_FWD_DEFINED__
typedef interface IClass IClass;
#ifdef __cplusplus
interface IClass;
#endif /* __cplusplus */
#endif

/* Headers for imported files */


#ifdef __cplusplus
extern "C" {
#endif

/*****************************************************************************
 * IClass interface
 */
#ifndef __IClass_INTERFACE_DEFINED__
#define __IClass_INTERFACE_DEFINED__

DEFINE_GUID(IID_IClass, 0xf1072a57, 0x214f, 0x4ee2, 0x83,0x77, 0x14,0xef,0x14,0x0c,0xd9,0xf3);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("f1072a57-214f-4ee2-8377-14ef140cd9f3")
IClass
{
    virtual void * STDMETHODCALLTYPE GetFixupInfo(
        void **arg) = 0;

    virtual void STDMETHODCALLTYPE NoReturn(
        void ****arg) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IClass, 0xf1072a57, 0x214f, 0x4ee2, 0x83,0x77, 0x14,0xef,0x14,0x0c,0xd9,0xf3)
#endif
#else
typedef struct IClassVtbl {
    BEGIN_INTERFACE

    /*** IClass methods ***/
    void * (STDMETHODCALLTYPE *GetFixupInfo)(
        IClass *This,
        void **arg);

    void (STDMETHODCALLTYPE *NoReturn)(
        IClass *This,
        void ****arg);

    END_INTERFACE
} IClassVtbl;

interface IClass {
    CONST_VTBL IClassVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IClass methods ***/
#define IClass_GetFixupInfo(This,arg) (This)->lpVtbl->GetFixupInfo(This,arg)
#define IClass_NoReturn(This,arg) (This)->lpVtbl->NoReturn(This,arg)
#else
/*** IClass methods ***/
static inline void * IClass_GetFixupInfo(IClass* This,void **arg) {
    return This->lpVtbl->GetFixupInfo(This,arg);
}
static inline void IClass_NoReturn(IClass* This,void ****arg) {
    This->lpVtbl->NoReturn(This,arg);
}
#endif
#endif

#endif


#endif  /* __IClass_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __void_h__ */
